### ISSUE TITLE
use jupyterlite in the documentation

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#470]
**Describe the bug**

In the current implementation of the documentation, the user cannot interact with the generated widgets in examples. It could be interesting to see how we can integrate jupyterlite to replace jupyter-sphinx.

ref : https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/jupyterlite.html

**Todo**

- [x] build the wheel of the lib (we currently only serve the archive
- [ ] config a jupyterlite server 
- [ ] serve it in the doc
